export type ShortcutCategory =
  | "blocks"
  | "formatting"
  | "lists"
  | "font"
  | "actions"
  | "markdown"
  | "triggers"

export interface ShortcutItem {
  id: string
  action: string
  description: string
  category: ShortcutCategory
  mac: string[]
  windows: string[]
  badge?: string
}

export const SHORTCUT_CATEGORIES: {
  id: ShortcutCategory | "all"
  label: string
}[] = [
  { id: "all", label: "All Shortcuts" },
  { id: "blocks", label: "Blocks & Headings" },
  { id: "formatting", label: "Text Styling" },
  { id: "lists", label: "Lists & Tasks" },
  { id: "font", label: "Font & Alignment" },
  { id: "actions", label: "Editing & History" },
  { id: "markdown", label: "Markdown Shortcuts" },
  { id: "triggers", label: "Triggers & Navigation" },
]

export const SHORTCUTS_DATA: ShortcutItem[] = [
  // Blocks
  {
    id: "normal",
    action: "Normal Text",
    description: "Convert current block to standard paragraph",
    category: "blocks",
    mac: ["⌘", "⌥", "0"],
    windows: ["Ctrl", "Alt", "0"],
    badge: "Popular",
  },
  {
    id: "h1",
    action: "Heading 1",
    description: "Large major section heading",
    category: "blocks",
    mac: ["⌘", "⌥", "1"],
    windows: ["Ctrl", "Alt", "1"],
    badge: "Popular",
  },
  {
    id: "h2",
    action: "Heading 2",
    description: "Medium subsection heading",
    category: "blocks",
    mac: ["⌘", "⌥", "2"],
    windows: ["Ctrl", "Alt", "2"],
  },
  {
    id: "h3",
    action: "Heading 3",
    description: "Small topic heading",
    category: "blocks",
    mac: ["⌘", "⌥", "3"],
    windows: ["Ctrl", "Alt", "3"],
  },
  {
    id: "code-block",
    action: "Code Block",
    description: "Preformatted code block with syntax highlight",
    category: "blocks",
    mac: ["⌘", "⌥", "C"],
    windows: ["Ctrl", "Alt", "C"],
    badge: "Developer",
  },
  {
    id: "insert-code-block",
    action: "Insert Code Block",
    description: "Insert new code block snippet",
    category: "blocks",
    mac: ["⌘", "⇧", "C"],
    windows: ["Ctrl", "Shift", "C"],
  },
  {
    id: "quote",
    action: "Quote Block",
    description: "Callout blockquote for citations or highlights",
    category: "blocks",
    mac: ["⌘", "⇧", "Q"],
    windows: ["Ctrl", "Shift", "Q"],
  },
  {
    id: "add-comment",
    action: "Add Note / Comment",
    description: "Attach comment or sticky note to selection",
    category: "blocks",
    mac: ["⌘", "⌥", "M"],
    windows: ["Ctrl", "Alt", "M"],
  },
  {
    id: "page-break",
    action: "Page Break",
    description: "Insert hard page break divider for print/export",
    category: "blocks",
    mac: ["⌘", "Enter"],
    windows: ["Ctrl", "Enter"],
  },

  // Lists & Tasks
  {
    id: "numbered-list",
    action: "Numbered List",
    description: "Create ordered step-by-step list",
    category: "lists",
    mac: ["⌘", "⇧", "7"],
    windows: ["Ctrl", "Shift", "7"],
  },
  {
    id: "bullet-list",
    action: "Bullet List",
    description: "Create unordered bulleted item list",
    category: "lists",
    mac: ["⌘", "⇧", "8"],
    windows: ["Ctrl", "Shift", "8"],
  },
  {
    id: "check-list",
    action: "Check List",
    description: "Create interactive todo checklist items",
    category: "lists",
    mac: ["⌘", "⇧", "9"],
    windows: ["Ctrl", "Shift", "9"],
    badge: "Tasks",
  },
  {
    id: "indent-list",
    action: "Indent List Item",
    description: "Nest item one level deeper into sublist",
    category: "lists",
    mac: ["Tab"],
    windows: ["Tab"],
  },
  {
    id: "outdent-list",
    action: "Outdent List Item",
    description: "Lift item one level out of sublist",
    category: "lists",
    mac: ["⇧", "Tab"],
    windows: ["Shift", "Tab"],
  },

  // Formatting
  {
    id: "bold",
    action: "Bold Text",
    description: "Make selected text bold and prominent",
    category: "formatting",
    mac: ["⌘", "B"],
    windows: ["Ctrl", "B"],
    badge: "Popular",
  },
  {
    id: "italic",
    action: "Italic Text",
    description: "Slant selected text for emphasis",
    category: "formatting",
    mac: ["⌘", "I"],
    windows: ["Ctrl", "I"],
  },
  {
    id: "underline",
    action: "Underline Text",
    description: "Add solid underline below selected text",
    category: "formatting",
    mac: ["⌘", "U"],
    windows: ["Ctrl", "U"],
  },
  {
    id: "strikethrough",
    action: "Strikethrough",
    description: "Draw horizontal line through text",
    category: "formatting",
    mac: ["⌘", "⇧", "S"],
    windows: ["Ctrl", "Shift", "S"],
  },
  {
    id: "inline-code",
    action: "Inline Code",
    description: "Style text as monospace inline snippet",
    category: "formatting",
    mac: ["⌘", "E"],
    windows: ["Ctrl", "E"],
  },
  {
    id: "insert-link",
    action: "Insert / Edit Link",
    description: "Add or modify hyperlink on selection",
    category: "formatting",
    mac: ["⌘", "K"],
    windows: ["Ctrl", "K"],
    badge: "Popular",
  },
  {
    id: "subscript",
    action: "Subscript",
    description: "Lower text position for chemical formulas/footnotes",
    category: "formatting",
    mac: ["⌘", ","],
    windows: ["Ctrl", ","],
  },
  {
    id: "superscript",
    action: "Superscript",
    description: "Raise text position for mathematical powers/exponents",
    category: "formatting",
    mac: ["⌘", "."],
    windows: ["Ctrl", "."],
  },
  {
    id: "clear-formatting",
    action: "Clear Formatting",
    description: "Remove all styling and reset to plain text",
    category: "formatting",
    mac: ["⌘", "\\"],
    windows: ["Ctrl", "\\"],
  },

  // Font & Alignment
  {
    id: "increase-font",
    action: "Increase Font Size",
    description: "Step up font size of active text",
    category: "font",
    mac: ["⌘", "⇧", "."],
    windows: ["Ctrl", "Shift", "."],
  },
  {
    id: "decrease-font",
    action: "Decrease Font Size",
    description: "Step down font size of active text",
    category: "font",
    mac: ["⌘", "⇧", ","],
    windows: ["Ctrl", "Shift", ","],
  },
  {
    id: "align-left",
    action: "Align Left",
    description: "Flush paragraph to left edge",
    category: "font",
    mac: ["⌘", "⇧", "L"],
    windows: ["Ctrl", "Shift", "L"],
  },
  {
    id: "align-center",
    action: "Align Center",
    description: "Center paragraph horizontally",
    category: "font",
    mac: ["⌘", "⇧", "E"],
    windows: ["Ctrl", "Shift", "E"],
  },
  {
    id: "align-right",
    action: "Align Right",
    description: "Flush paragraph to right edge",
    category: "font",
    mac: ["⌘", "⇧", "R"],
    windows: ["Ctrl", "Shift", "R"],
  },
  {
    id: "align-justify",
    action: "Justify Content",
    description: "Evenly space text to align with both edges",
    category: "font",
    mac: ["⌘", "⇧", "J"],
    windows: ["Ctrl", "Shift", "J"],
  },

  // Editing & History
  {
    id: "undo",
    action: "Undo",
    description: "Revert last editing change",
    category: "actions",
    mac: ["⌘", "Z"],
    windows: ["Ctrl", "Z"],
  },
  {
    id: "redo",
    action: "Redo",
    description: "Re-apply previously undone change",
    category: "actions",
    mac: ["⌘", "⇧", "Z"],
    windows: ["Ctrl", "Y"],
  },
  {
    id: "select-all",
    action: "Select All",
    description: "Select all content within document",
    category: "actions",
    mac: ["⌘", "A"],
    windows: ["Ctrl", "A"],
  },
  {
    id: "copy",
    action: "Copy Selection",
    description: "Copy selected blocks or text to clipboard",
    category: "actions",
    mac: ["⌘", "C"],
    windows: ["Ctrl", "C"],
  },
  {
    id: "cut",
    action: "Cut Selection",
    description: "Cut selection to clipboard",
    category: "actions",
    mac: ["⌘", "X"],
    windows: ["Ctrl", "X"],
  },
  {
    id: "paste",
    action: "Paste Clipboard",
    description: "Paste clipboard content into document",
    category: "actions",
    mac: ["⌘", "V"],
    windows: ["Ctrl", "V"],
  },

  // Markdown Typing Shortcuts
  {
    id: "md-h1",
    action: "# + Space",
    description: "Type at line start to trigger Heading 1",
    category: "markdown",
    mac: ["#", "Space"],
    windows: ["#", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-h2",
    action: "## + Space",
    description: "Type at line start to trigger Heading 2",
    category: "markdown",
    mac: ["##", "Space"],
    windows: ["##", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-h3",
    action: "### + Space",
    description: "Type at line start to trigger Heading 3",
    category: "markdown",
    mac: ["###", "Space"],
    windows: ["###", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-bullet",
    action: "- or * + Space",
    description: "Type at line start to start a bulleted list",
    category: "markdown",
    mac: ["-", "Space"],
    windows: ["-", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-number",
    action: "1. + Space",
    description: "Type at line start to start a numbered list",
    category: "markdown",
    mac: ["1.", "Space"],
    windows: ["1.", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-check",
    action: "[] or [ ] + Space",
    description: "Type at line start to start a checklist item",
    category: "markdown",
    mac: ["[]", "Space"],
    windows: ["[]", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-quote",
    action: "> + Space",
    description: "Type at line start to start a blockquote",
    category: "markdown",
    mac: [">", "Space"],
    windows: [">", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-code",
    action: "``` + Space",
    description: "Type three backticks and space to insert code block",
    category: "markdown",
    mac: ["```", "Space"],
    windows: ["```", "Space"],
    badge: "Markdown",
  },
  {
    id: "md-divider",
    action: "---",
    description: "Type three hyphens and Enter to insert horizontal line",
    category: "markdown",
    mac: ["---", "Enter"],
    windows: ["---", "Enter"],
    badge: "Markdown",
  },

  // Triggers & Navigation
  {
    id: "slash-menu",
    action: "Slash Command Menu",
    description: "Open full palette of insertable blocks and templates",
    category: "triggers",
    mac: ["/"],
    windows: ["/"],
    badge: "Essential",
  },
  {
    id: "mention",
    action: "Mention Collaborator",
    description: "Mention team member or insert tag link",
    category: "triggers",
    mac: ["@"],
    windows: ["@"],
  },
  {
    id: "emoji",
    action: "Emoji Autocomplete",
    description: "Type colon followed by keyword to insert emoji",
    category: "triggers",
    mac: [":"],
    windows: [":"],
  },
  {
    id: "shortcuts-modal",
    action: "Show Shortcuts Modal",
    description: "Open this keyboard shortcuts quick reference guide",
    category: "triggers",
    mac: ["⌘", "/"],
    windows: ["Ctrl", "/"],
    badge: "Help",
  },
]
