/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as BlocksPreviewSlugRouteImport } from './routes/blocks-preview.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminResourcesRouteImport } from './routes/admin/resources'
import { Route as AdminRegistryRouteImport } from './routes/admin/registry'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as SiteResourcesIndexRouteImport } from './routes/_site/resources/index'
import { Route as SiteComponentUiIndexRouteImport } from './routes/_site/component-ui/index'
import { Route as SiteColophonIndexRouteImport } from './routes/_site/colophon/index'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog/index'
import { Route as SiteBlocksIndexRouteImport } from './routes/_site/blocks/index'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as AdminPostsIdRouteImport } from './routes/admin/posts/$id'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog/$slug'
import { Route as SiteComponentUiCategoryIndexRouteImport } from './routes/_site/component-ui/$category/index'
import { Route as SiteBlocksCategoryIndexRouteImport } from './routes/_site/blocks/$category/index'
import { Route as SiteComponentUiCategorySlugRouteImport } from './routes/_site/component-ui/$category/$slug'
import { Route as SiteBlocksCategorySlugRouteImport } from './routes/_site/blocks/$category/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const BlocksPreviewSlugRoute = BlocksPreviewSlugRouteImport.update({
  id: '/blocks-preview/$slug',
  path: '/blocks-preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistryRoute = AdminRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteResourcesIndexRoute = SiteResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteComponentUiIndexRoute = SiteComponentUiIndexRouteImport.update({
  id: '/component-ui/',
  path: '/component-ui/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteColophonIndexRoute = SiteColophonIndexRouteImport.update({
  id: '/colophon/',
  path: '/colophon/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBlocksIndexRoute = SiteBlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteComponentUiCategoryIndexRoute =
  SiteComponentUiCategoryIndexRouteImport.update({
    id: '/component-ui/$category/',
    path: '/component-ui/$category/',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteBlocksCategoryIndexRoute = SiteBlocksCategoryIndexRouteImport.update({
  id: '/blocks/$category/',
  path: '/blocks/$category/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteComponentUiCategorySlugRoute =
  SiteComponentUiCategorySlugRouteImport.update({
    id: '/component-ui/$category/$slug',
    path: '/component-ui/$category/$slug',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteBlocksCategorySlugRoute = SiteBlocksCategorySlugRouteImport.update({
  id: '/blocks/$category/$slug',
  path: '/blocks/$category/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/registry': typeof AdminRegistryRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blocks-preview/$slug': typeof BlocksPreviewSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/blocks/': typeof SiteBlocksIndexRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/colophon/': typeof SiteColophonIndexRoute
  '/component-ui/': typeof SiteComponentUiIndexRoute
  '/resources/': typeof SiteResourcesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/blocks/$category/$slug': typeof SiteBlocksCategorySlugRoute
  '/component-ui/$category/$slug': typeof SiteComponentUiCategorySlugRoute
  '/blocks/$category/': typeof SiteBlocksCategoryIndexRoute
  '/component-ui/$category/': typeof SiteComponentUiCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/registry': typeof AdminRegistryRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blocks-preview/$slug': typeof BlocksPreviewSlugRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/blocks': typeof SiteBlocksIndexRoute
  '/blog': typeof SiteBlogIndexRoute
  '/colophon': typeof SiteColophonIndexRoute
  '/component-ui': typeof SiteComponentUiIndexRoute
  '/resources': typeof SiteResourcesIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/blocks/$category/$slug': typeof SiteBlocksCategorySlugRoute
  '/component-ui/$category/$slug': typeof SiteComponentUiCategorySlugRoute
  '/blocks/$category': typeof SiteBlocksCategoryIndexRoute
  '/component-ui/$category': typeof SiteComponentUiCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/$': typeof AdminSplatRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/registry': typeof AdminRegistryRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blocks-preview/$slug': typeof BlocksPreviewSlugRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/_site/blocks/': typeof SiteBlocksIndexRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/colophon/': typeof SiteColophonIndexRoute
  '/_site/component-ui/': typeof SiteComponentUiIndexRoute
  '/_site/resources/': typeof SiteResourcesIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/_site/blocks/$category/$slug': typeof SiteBlocksCategorySlugRoute
  '/_site/component-ui/$category/$slug': typeof SiteComponentUiCategorySlugRoute
  '/_site/blocks/$category/': typeof SiteBlocksCategoryIndexRoute
  '/_site/component-ui/$category/': typeof SiteComponentUiCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/$'
    | '/admin/categories'
    | '/admin/groups'
    | '/admin/registry'
    | '/admin/resources'
    | '/admin/settings'
    | '/blocks-preview/$slug'
    | '/admin/'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/blocks/'
    | '/blog/'
    | '/colophon/'
    | '/component-ui/'
    | '/resources/'
    | '/admin/posts/'
    | '/blocks/$category/$slug'
    | '/component-ui/$category/$slug'
    | '/blocks/$category/'
    | '/component-ui/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/$'
    | '/admin/categories'
    | '/admin/groups'
    | '/admin/registry'
    | '/admin/resources'
    | '/admin/settings'
    | '/blocks-preview/$slug'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/blocks'
    | '/blog'
    | '/colophon'
    | '/component-ui'
    | '/resources'
    | '/admin/posts'
    | '/blocks/$category/$slug'
    | '/component-ui/$category/$slug'
    | '/blocks/$category'
    | '/component-ui/$category'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/$'
    | '/admin/categories'
    | '/admin/groups'
    | '/admin/registry'
    | '/admin/resources'
    | '/admin/settings'
    | '/blocks-preview/$slug'
    | '/_site/'
    | '/admin/'
    | '/_site/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/_site/blocks/'
    | '/_site/blog/'
    | '/_site/colophon/'
    | '/_site/component-ui/'
    | '/_site/resources/'
    | '/admin/posts/'
    | '/_site/blocks/$category/$slug'
    | '/_site/component-ui/$category/$slug'
    | '/_site/blocks/$category/'
    | '/_site/component-ui/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlocksPreviewSlugRoute: typeof BlocksPreviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/blocks-preview/$slug': {
      id: '/blocks-preview/$slug'
      path: '/blocks-preview/$slug'
      fullPath: '/blocks-preview/$slug'
      preLoaderRoute: typeof BlocksPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registry': {
      id: '/admin/registry'
      path: '/registry'
      fullPath: '/admin/registry'
      preLoaderRoute: typeof AdminRegistryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/resources/': {
      id: '/_site/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof SiteResourcesIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/component-ui/': {
      id: '/_site/component-ui/'
      path: '/component-ui'
      fullPath: '/component-ui/'
      preLoaderRoute: typeof SiteComponentUiIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/colophon/': {
      id: '/_site/colophon/'
      path: '/colophon'
      fullPath: '/colophon/'
      preLoaderRoute: typeof SiteColophonIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blocks/': {
      id: '/_site/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof SiteBlocksIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/component-ui/$category/': {
      id: '/_site/component-ui/$category/'
      path: '/component-ui/$category'
      fullPath: '/component-ui/$category/'
      preLoaderRoute: typeof SiteComponentUiCategoryIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blocks/$category/': {
      id: '/_site/blocks/$category/'
      path: '/blocks/$category'
      fullPath: '/blocks/$category/'
      preLoaderRoute: typeof SiteBlocksCategoryIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/component-ui/$category/$slug': {
      id: '/_site/component-ui/$category/$slug'
      path: '/component-ui/$category/$slug'
      fullPath: '/component-ui/$category/$slug'
      preLoaderRoute: typeof SiteComponentUiCategorySlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blocks/$category/$slug': {
      id: '/_site/blocks/$category/$slug'
      path: '/blocks/$category/$slug'
      fullPath: '/blocks/$category/$slug'
      preLoaderRoute: typeof SiteBlocksCategorySlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteBlocksIndexRoute: typeof SiteBlocksIndexRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteColophonIndexRoute: typeof SiteColophonIndexRoute
  SiteComponentUiIndexRoute: typeof SiteComponentUiIndexRoute
  SiteResourcesIndexRoute: typeof SiteResourcesIndexRoute
  SiteBlocksCategorySlugRoute: typeof SiteBlocksCategorySlugRoute
  SiteComponentUiCategorySlugRoute: typeof SiteComponentUiCategorySlugRoute
  SiteBlocksCategoryIndexRoute: typeof SiteBlocksCategoryIndexRoute
  SiteComponentUiCategoryIndexRoute: typeof SiteComponentUiCategoryIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteBlocksIndexRoute: SiteBlocksIndexRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteColophonIndexRoute: SiteColophonIndexRoute,
  SiteComponentUiIndexRoute: SiteComponentUiIndexRoute,
  SiteResourcesIndexRoute: SiteResourcesIndexRoute,
  SiteBlocksCategorySlugRoute: SiteBlocksCategorySlugRoute,
  SiteComponentUiCategorySlugRoute: SiteComponentUiCategorySlugRoute,
  SiteBlocksCategoryIndexRoute: SiteBlocksCategoryIndexRoute,
  SiteComponentUiCategoryIndexRoute: SiteComponentUiCategoryIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminRegistryRoute: typeof AdminRegistryRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminRegistryRoute: AdminRegistryRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlocksPreviewSlugRoute: BlocksPreviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
