/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as BlocksPreviewSlugRouteImport } from './routes/blocks-preview.$slug'
import { Route as SiteResourcesIndexRouteImport } from './routes/_site/resources/index'
import { Route as SiteComponentUiIndexRouteImport } from './routes/_site/component-ui/index'
import { Route as SiteColophonIndexRouteImport } from './routes/_site/colophon/index'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog/index'
import { Route as SiteBlocksIndexRouteImport } from './routes/_site/blocks/index'
import { Route as SiteComponentUiCategoryIndexRouteImport } from './routes/_site/component-ui/$category/index'
import { Route as SiteBlocksCategoryIndexRouteImport } from './routes/_site/blocks/$category/index'
import { Route as SiteComponentUiCategorySlugRouteImport } from './routes/_site/component-ui/$category/$slug'
import { Route as SiteBlocksCategorySlugRouteImport } from './routes/_site/blocks/$category/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const BlocksPreviewSlugRoute = BlocksPreviewSlugRouteImport.update({
  id: '/blocks-preview/$slug',
  path: '/blocks-preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteResourcesIndexRoute = SiteResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteComponentUiIndexRoute = SiteComponentUiIndexRouteImport.update({
  id: '/component-ui/',
  path: '/component-ui/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteColophonIndexRoute = SiteColophonIndexRouteImport.update({
  id: '/colophon/',
  path: '/colophon/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteBlocksIndexRoute = SiteBlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteComponentUiCategoryIndexRoute =
  SiteComponentUiCategoryIndexRouteImport.update({
    id: '/component-ui/$category/',
    path: '/component-ui/$category/',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteBlocksCategoryIndexRoute = SiteBlocksCategoryIndexRouteImport.update({
  id: '/blocks/$category/',
  path: '/blocks/$category/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteComponentUiCategorySlugRoute =
  SiteComponentUiCategorySlugRouteImport.update({
    id: '/component-ui/$category/$slug',
    path: '/component-ui/$category/$slug',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteBlocksCategorySlugRoute = SiteBlocksCategorySlugRouteImport.update({
  id: '/blocks/$category/$slug',
  path: '/blocks/$category/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blocks-preview/$slug': typeof BlocksPreviewSlugRoute
  '/blocks/': typeof SiteBlocksIndexRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/colophon/': typeof SiteColophonIndexRoute
  '/component-ui/': typeof SiteComponentUiIndexRoute
  '/resources/': typeof SiteResourcesIndexRoute
  '/blocks/$category/$slug': typeof SiteBlocksCategorySlugRoute
  '/component-ui/$category/$slug': typeof SiteComponentUiCategorySlugRoute
  '/blocks/$category/': typeof SiteBlocksCategoryIndexRoute
  '/component-ui/$category/': typeof SiteComponentUiCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blocks-preview/$slug': typeof BlocksPreviewSlugRoute
  '/': typeof SiteIndexRoute
  '/blocks': typeof SiteBlocksIndexRoute
  '/blog': typeof SiteBlogIndexRoute
  '/colophon': typeof SiteColophonIndexRoute
  '/component-ui': typeof SiteComponentUiIndexRoute
  '/resources': typeof SiteResourcesIndexRoute
  '/blocks/$category/$slug': typeof SiteBlocksCategorySlugRoute
  '/component-ui/$category/$slug': typeof SiteComponentUiCategorySlugRoute
  '/blocks/$category': typeof SiteBlocksCategoryIndexRoute
  '/component-ui/$category': typeof SiteComponentUiCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blocks-preview/$slug': typeof BlocksPreviewSlugRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blocks/': typeof SiteBlocksIndexRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/colophon/': typeof SiteColophonIndexRoute
  '/_site/component-ui/': typeof SiteComponentUiIndexRoute
  '/_site/resources/': typeof SiteResourcesIndexRoute
  '/_site/blocks/$category/$slug': typeof SiteBlocksCategorySlugRoute
  '/_site/component-ui/$category/$slug': typeof SiteComponentUiCategorySlugRoute
  '/_site/blocks/$category/': typeof SiteBlocksCategoryIndexRoute
  '/_site/component-ui/$category/': typeof SiteComponentUiCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blocks-preview/$slug'
    | '/blocks/'
    | '/blog/'
    | '/colophon/'
    | '/component-ui/'
    | '/resources/'
    | '/blocks/$category/$slug'
    | '/component-ui/$category/$slug'
    | '/blocks/$category/'
    | '/component-ui/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blocks-preview/$slug'
    | '/'
    | '/blocks'
    | '/blog'
    | '/colophon'
    | '/component-ui'
    | '/resources'
    | '/blocks/$category/$slug'
    | '/component-ui/$category/$slug'
    | '/blocks/$category'
    | '/component-ui/$category'
  id:
    | '__root__'
    | '/_site'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blocks-preview/$slug'
    | '/_site/'
    | '/_site/blocks/'
    | '/_site/blog/'
    | '/_site/colophon/'
    | '/_site/component-ui/'
    | '/_site/resources/'
    | '/_site/blocks/$category/$slug'
    | '/_site/component-ui/$category/$slug'
    | '/_site/blocks/$category/'
    | '/_site/component-ui/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlocksPreviewSlugRoute: typeof BlocksPreviewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/blocks-preview/$slug': {
      id: '/blocks-preview/$slug'
      path: '/blocks-preview/$slug'
      fullPath: '/blocks-preview/$slug'
      preLoaderRoute: typeof BlocksPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/resources/': {
      id: '/_site/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof SiteResourcesIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/component-ui/': {
      id: '/_site/component-ui/'
      path: '/component-ui'
      fullPath: '/component-ui/'
      preLoaderRoute: typeof SiteComponentUiIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/colophon/': {
      id: '/_site/colophon/'
      path: '/colophon'
      fullPath: '/colophon/'
      preLoaderRoute: typeof SiteColophonIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blocks/': {
      id: '/_site/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof SiteBlocksIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/component-ui/$category/': {
      id: '/_site/component-ui/$category/'
      path: '/component-ui/$category'
      fullPath: '/component-ui/$category/'
      preLoaderRoute: typeof SiteComponentUiCategoryIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blocks/$category/': {
      id: '/_site/blocks/$category/'
      path: '/blocks/$category'
      fullPath: '/blocks/$category/'
      preLoaderRoute: typeof SiteBlocksCategoryIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/component-ui/$category/$slug': {
      id: '/_site/component-ui/$category/$slug'
      path: '/component-ui/$category/$slug'
      fullPath: '/component-ui/$category/$slug'
      preLoaderRoute: typeof SiteComponentUiCategorySlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/blocks/$category/$slug': {
      id: '/_site/blocks/$category/$slug'
      path: '/blocks/$category/$slug'
      fullPath: '/blocks/$category/$slug'
      preLoaderRoute: typeof SiteBlocksCategorySlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlocksIndexRoute: typeof SiteBlocksIndexRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteColophonIndexRoute: typeof SiteColophonIndexRoute
  SiteComponentUiIndexRoute: typeof SiteComponentUiIndexRoute
  SiteResourcesIndexRoute: typeof SiteResourcesIndexRoute
  SiteBlocksCategorySlugRoute: typeof SiteBlocksCategorySlugRoute
  SiteComponentUiCategorySlugRoute: typeof SiteComponentUiCategorySlugRoute
  SiteBlocksCategoryIndexRoute: typeof SiteBlocksCategoryIndexRoute
  SiteComponentUiCategoryIndexRoute: typeof SiteComponentUiCategoryIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteBlocksIndexRoute: SiteBlocksIndexRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteColophonIndexRoute: SiteColophonIndexRoute,
  SiteComponentUiIndexRoute: SiteComponentUiIndexRoute,
  SiteResourcesIndexRoute: SiteResourcesIndexRoute,
  SiteBlocksCategorySlugRoute: SiteBlocksCategorySlugRoute,
  SiteComponentUiCategorySlugRoute: SiteComponentUiCategorySlugRoute,
  SiteBlocksCategoryIndexRoute: SiteBlocksCategoryIndexRoute,
  SiteComponentUiCategoryIndexRoute: SiteComponentUiCategoryIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlocksPreviewSlugRoute: BlocksPreviewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
